services:

  ###########################
  # DEPENDENCIES            #
  ###########################

  # Generate RSA key for xtm-composer (PKCS#8 format)
  rsa-key-generator:
    image: alpine/openssl:latest
    volumes:
      - rsakeys:/keys
    entrypoint: ["/bin/ash"]
    networks:
      - soc-network
    command: ["-c", "if [ ! -f /keys/private_key.pem ]; then openssl genpkey -algorithm RSA -out /keys/private_key.pem -pkeyopt rsa_keygen_bits:4096; fi && tail -f /dev/null"]
    healthcheck:
      test: ["CMD", "test", "-f", "/keys/private_key.pem"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
  redis:
    image: redis:8.6.1
    restart: always
    volumes:
      - redisdata:/data
    networks:
      - soc-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.12
    hostname: opencti-elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
    - "9200:9200"
    networks:
      - soc-network
    environment:
      # Comment-out the line below for a cluster of multiple nodes
      - discovery.type=single-node
      # Uncomment the line below below for a cluster of multiple nodes
      # - cluster.name=docker-cluster
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - thread_pool.search.queue_size=5000
      - logger.org.elasticsearch.discovery="ERROR"
      - "ES_JAVA_OPTS=-Xms${ELASTIC_MEMORY_SIZE} -Xmx${ELASTIC_MEMORY_SIZE}"
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://opencti-elasticsearch:9200/_cluster/health?wait_for_status=yellow >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 50
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    networks:
      - soc-network
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}    
    command: server /data
    restart: always
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 3
  rabbitmq:
    image: rabbitmq:4.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_NODENAME=rabbit01@localhost
    volumes:
      - type: bind
        source: ./rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf 
      - amqpdata:/var/lib/rabbitmq
    networks:
      - soc-network
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  ###########################
  # COMMON                  #
  ###########################

  xtm-composer:
    image: filigran/xtm-composer:latest
    platform: linux/amd64
    environment:
      - MANAGER__ID=${XTM_COMPOSER_ID}
      - "MANAGER__NAME=XTM Integrations Manager"
      - MANAGER__CREDENTIALS_KEY_FILEPATH=/keys/private_key.pem
      - OPENCTI__ENABLE=true
      - OPENCTI__URL=http://opencti:8080
      - OPENCTI__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - OPENCTI__DAEMON__SELECTOR=docker
      - OPENCTI__DAEMON__DOCKER__NETWORK_MODE=soc-network
    networks:
      - soc-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - rsakeys:/keys:ro  # RSA key mounted as read-only
    depends_on:
      rsa-key-generator:
        condition: service_healthy
      opencti:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always

  ###########################
  # OPENCTI                 #
  ###########################
  
  opencti:
    image: opencti/platform:7.260515.0
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=8080
      - APP__BASE_URL=${OPENCTI_EXTERNAL_SCHEME}://${OPENCTI_HOST}:${OPENCTI_PORT}
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__ENCRYPTION_KEY=${OPENCTI_ENCRYPTION_KEY}
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://opencti-elasticsearch:9200
      - ELASTICSEARCH__NUMBER_OF_REPLICAS=0
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__PORT=25
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
      - APP__HEALTH_ACCESS_KEY=${OPENCTI_HEALTHCHECK_ACCESS_KEY}
    ports:
      - "${OPENCTI_PORT}:8080"
    networks:
      - soc-network
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always
    healthcheck:
      test:  ["CMD", "wget", "-qO-", "http://opencti:8080/health?health_access_key=${OPENCTI_HEALTHCHECK_ACCESS_KEY}"]
      interval: 10s
      timeout: 5s
      retries: 20
  worker:
    image: opencti/worker:7.260515.0
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
    networks:
      - soc-network
    depends_on:
      opencti:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 3
    restart: always

  ###########################
  # OPENCTI CONNECTORS      #
  ###########################

  connector-export-file-stix:
    image: opencti/connector-export-file-stix:7.260515.0
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_STIX_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileStix2
      - CONNECTOR_SCOPE=application/json
    restart: always
    depends_on:
      opencti:
        condition: service_healthy
    networks:
      - soc-network
  connector-export-file-csv:
    image: opencti/connector-export-file-csv:7.260515.0
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_CSV_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=text/csv
    networks:
      - soc-network
    restart: always
    depends_on:
      opencti:
        condition: service_healthy
  connector-export-file-txt:
    image: opencti/connector-export-file-txt:7.260515.0
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_TXT_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileTxt
      - CONNECTOR_SCOPE=text/plain
    networks:
      - soc-network
    restart: always
    depends_on:
      opencti:
        condition: service_healthy
  connector-import-file-stix:
    image: opencti/connector-import-file-stix:7.260515.0
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_FILE_STIX_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFileStix
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=true # Validate any bundle before import
      - CONNECTOR_SCOPE=application/json,text/xml
      - CONNECTOR_AUTO=true # Enable/disable auto-import of file
    networks:
      - soc-network
    restart: always
    depends_on:
      opencti:
        condition: service_healthy
  connector-import-document:
    image: opencti/connector-import-document:7.260515.0
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_DOCUMENT_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportDocument
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=true # Validate any bundle before import
      - CONNECTOR_SCOPE=application/pdf,text/plain,text/html
      - CONNECTOR_AUTO=true # Enable/disable auto-import of file
      - CONNECTOR_ONLY_CONTEXTUAL=false # Only extract data related to an entity (a report, a threat actor, etc.)
      - IMPORT_DOCUMENT_CREATE_INDICATOR=true
    networks:
      - soc-network
    restart: always
    depends_on:
      opencti:
        condition: service_healthy
  connector-import-file-yara:
    image: opencti/connector-import-file-yara:7.260515.0
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_FILE_YARA_ID} # Valid UUIDv4
      - CONNECTOR_NAME=ImportFileYARA
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=true # Validate any bundle before import
      - CONNECTOR_SCOPE=text/yara+plain
      - CONNECTOR_AUTO=false # Enable/disable auto-import of file
      - YARA_IMPORT_FILE_SPLIT_RULES=true
    networks:
      - soc-network
    restart: always
    depends_on:
      opencti:
        condition: service_healthy
  connector-analysis:
    image: opencti/connector-import-document:7.260515.0
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_ANALYSIS_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_ANALYSIS
      - CONNECTOR_NAME=ImportDocumentAnalysis
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=false # Validate any bundle before import
      - CONNECTOR_SCOPE=application/pdf,text/plain,text/html
      - CONNECTOR_AUTO=true # Enable/disable auto-import of file
      - CONNECTOR_ONLY_CONTEXTUAL=false # Only extract data related to an entity (a report, a threat actor, etc.)
    networks:
      - soc-network
    restart: always
    depends_on:
      opencti:
        condition: service_healthy
  connector-import-external-reference:
    image: opencti/connector-import-external-reference:7.260515.0
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_EXTERNAL_REFERENCE_ID}
      - CONNECTOR_NAME=ImportExternalReference
    networks:
      - soc-network
    restart: always
    depends_on:
      opencti:
        condition: service_healthy          

  ###########################
  # OPENCTI DEFAULT DATA    #
  ###########################

  connector-opencti:
    image: opencti/connector-opencti:7.260515.0
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_OPENCTI_ID}
      - "CONNECTOR_NAME=OpenCTI Datasets"
      - CONNECTOR_SCOPE=marking-definition,identity,location
      - CONNECTOR_AUTO_CREATE_SERVICE_ACCOUNT=true
      - CONNECTOR_AUTO_CREATE_SERVICE_ACCOUNT_CONFIDENCE_LEVEL=100
    networks:
      - soc-network
    restart: always
    depends_on:
      opencti:
        condition: service_healthy      
  connector-mitre:
    image: opencti/connector-mitre:7.260515.0
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MITRE_ID}
      - CONNECTOR_AUTO_CREATE_SERVICE_ACCOUNT=true
      - CONNECTOR_AUTO_CREATE_SERVICE_ACCOUNT_CONFIDENCE_LEVEL=75     
    networks:
      - soc-network 
    restart: always
    depends_on:
      opencti:
        condition: service_healthy    

  connector-abuseipdb-ipblacklist:
    image: opencti/connector-abuseipdb-ipblacklist:7.260515.0
    environment:
      # Connector's generic execution parameters
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      # Connector's definition parameters REQUIRED
      - CONNECTOR_ID=25c2066c-e36f-4ae0-818e-f7de4bbb7f8e
      - CONNECTOR_NAME=AbuseIPDB IP Blacklist
      - CONNECTOR_SCOPE=abuseipdb
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_DURATION_PERIOD=PT12H

      # Connector's custom execution parameters
      # - ABUSEIPDB_API_URL=https://api.abuseipdb.com/api/v2/blacklist
      - ABUSEIPDB_API_KEY=${ABUSEIPDB_API_KEY}
      - ABUSEIPDB_SCORE=75
      # - ABUSEIPDB_LIMIT=500000
      # - ABUSEIPDB_CREATE_INDICATOR=false
      # - ABUSEIPDB_TLP_LEVEL=clear
      # - ABUSEIPDB_IPVERSION=mixed
      # - ABUSEIPDB_EXCEPT_COUNTRY=
      # - ABUSEIPDB_ONLY_COUNTRY=
    networks:
      - soc-network
    restart: always  
    depends_on:
      opencti:
        condition: service_healthy   

  connector-thehive:
    image: opencti/connector-thehive:7.260515.0
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=e60169cc-faa1-4962-abc0-be39da560662
      - CONNECTOR_NAME=TheHive-connector
      - CONNECTOR_SCOPE=thehive
      - CONNECTOR_LOG_LEVEL=info
      - THEHIVE_URL=http://thehive:9000
      - THEHIVE_API_KEY=${THEHIVE_API_KEY}
      - THEHIVE_IMPORT_ATTACHMENTS=false
      - THEHIVE_CHECK_SSL=false
      - THEHIVE_ORGANIZATION_NAME=soc
      - THEHIVE_IMPORT_FROM_DATE=2021-01-01T00:00:00 # Optional
      - THEHIVE_IMPORT_ONLY_TLP=0,1,2,3,4
      - THEHIVE_IMPORT_ALERTS=true
      - "THEHIVE_SEVERITY_MAPPING=1:low,2:medium,3:high,4:critical"
      - THEHIVE_CASE_STATUS_MAPPING= # TheHive_ExtStatus_Text1:OpenCTI_Status_ID1,TheHive_ExtStatus_Text2:OpenCTI_Status_ID2
      - THEHIVE_TASK_STATUS_MAPPING= # Waiting:OpenCTI_Status_ID1,InProgress:OpenCTI_Status_ID2,Completed:OpenCTI_Status_ID2
      - THEHIVE_ALERT_STATUS_MAPPING= # TheHive_ExtStatus_Text1:OpenCTI_Status_ID1,TheHive_ExtStatus_Text2:OpenCTI_Status_ID2
      - THEHIVE_USER_MAPPING= # Format: TheHive_Assignee_Email1:OpenCTI_User_ID1,TheHive_Assignee_Email2:OpenCTI_User_ID2
      - THEHIVE_INTERVAL=5 # In minutes
      - THEHIVE_CASE_TAG_WHITELIST= # TAG_OK,TAG_GOOD
    networks:
      - soc-network
    restart: always
    depends_on:
      opencti:
        condition: service_healthy

  connector-malwarebazaar:
    image: opencti/connector-malwarebazaar:7.260515.0
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=b3e1f2a4-8c7d-4e5f-9a1b-2c3d4e5f6a7b
      - CONNECTOR_NAME=MalwareBazaar
      - CONNECTOR_SCOPE=Malware,StixFile,IPv4-Addr,Domain-Name,Url
      - CONNECTOR_LOG_LEVEL=info
      - MALWAREBAZAAR_API_KEY=${MALWAREBAZAAR_API_KEY}
      - MALWAREBAZAAR_UPDATE_EXISTING_DATA=false
      - MALWAREBAZAAR_INTERVAL=30
    networks:
      - soc-network
    restart: always
    depends_on:
      opencti:
        condition: service_healthy

  connector-virustotal:
    image: opencti/connector-virustotal:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=05b66e35-18a3-47aa-92fe-3b1ec61c7b65
      - CONNECTOR_NAME=VirusTotal
#      - CONNECTOR_SCOPE=StixFile,Artifact,IPv4-Addr,Domain-Name,Url,Hostname
      - CONNECTOR_AUTO=true # Enable/disable auto-enrichment of observables
#      - CONNECTOR_LOG_LEVEL=error
#      - CONNECTOR_EXPOSE_METRICS=false

      - VIRUSTOTAL_TOKEN=${VIRUSTOTAL_TOKEN}
#      - VIRUSTOTAL_MAX_TLP=TLP:AMBER
#      - VIRUSTOTAL_REPLACE_WITH_LOWER_SCORE=true # Whether to keep the higher of the VT or existing score (false) or force the score to be updated with the VT score even if its lower than existing score (true).
#      # File/Artifact specific config settings
#      - VIRUSTOTAL_FILE_CREATE_NOTE_FULL_REPORT=true # Whether or not to include the full report as a Note
      - VIRUSTOTAL_FILE_UPLOAD_UNSEEN_ARTIFACTS=true # Whether to upload artifacts (smaller than 32MB) that VirusTotal has no record of
#      - VIRUSTOTAL_FILE_INDICATOR_CREATE_POSITIVES=10 # Create an indicator for File/Artifact based observables once this positive threshold is reached. Note: specify 0 to disable indicator creation
#      - VIRUSTOTAL_FILE_INDICATOR_VALID_MINUTES=2880 # How long the indicator is valid for in minutes
#      - VIRUSTOTAL_FILE_INDICATOR_DETECT=true # Whether or not to set detection for the indicator to true
#      - VIRUSTOTAL_FILE_IMPORT_YARA=true # Whether or not import Crowdsourced YARA rules
#      # IP specific config settings
#      - VIRUSTOTAL_IP_INDICATOR_CREATE_POSITIVES=10 # Create an indicator for IPv4 based observables once this positive threshold is reached. Note: specify 0 to disable indicator creation
#      - VIRUSTOTAL_IP_INDICATOR_VALID_MINUTES=2880 # How long the indicator is valid for in minutes
#      - VIRUSTOTAL_IP_INDICATOR_DETECT=true # Whether or not to set detection for the indicator to true
#      - VIRUSTOTAL_IP_ADD_RELATIONSHIPS=false # Whether or not to add ASN and location resolution relationships
#      # Domain specific config settings
#      - VIRUSTOTAL_DOMAIN_INDICATOR_CREATE_POSITIVES=10 # Create an indicator for Domain based observables once this positive threshold is reached. Note: specify 0 to disable indicator creation
#      - VIRUSTOTAL_DOMAIN_INDICATOR_VALID_MINUTES=2880 # How long the indicator is valid for in minutes
#      - VIRUSTOTAL_DOMAIN_INDICATOR_DETECT=true # Whether or not to set detection for the indicator to true
#      - VIRUSTOTAL_DOMAIN_ADD_RELATIONSHIPS=false # Whether or not to add IP resolution relationships
#      # URL specific config settings
#      - VIRUSTOTAL_URL_UPLOAD_UNSEEN=true # Whether to upload URLs that VirusTotal has no record of for analysis
#      - VIRUSTOTAL_URL_INDICATOR_CREATE_POSITIVES=10 # Create an indicator for Url based observables once this positive threshold is reached. Note: specify 0 to disable indicator creation
#      - VIRUSTOTAL_URL_INDICATOR_VALID_MINUTES=2880 # How long the indicator is valid for in minutes
#      - VIRUSTOTAL_URL_INDICATOR_DETECT=true # Whether or not to set detection for the indicator to true
#      # Generic config settings for File, IP, Domain, URL
#      - VIRUSTOTAL_INCLUDE_ATTRIBUTES_IN_NOTE=false # Whether or not to include the attributes info in Note
    networks:
      - soc-network
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      opencti:
        condition: service_healthy

networks:
  soc-network:
    external: true

volumes:
  esdata:
  s3data:
  redisdata:
  amqpdata:
  rsakeys: